### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by yearnfar** [shi/crpm-lambda-container-puppeteer#1]
When you install puppeteer, chromium is already installed automatically。If you do not specify a browser, chromium is used by default。The google-chrome-stable you followed is not used，When you specify google-chrome-stable,  you will find that Lambda cannot start google-chrome-stable until it times out。

**Comment by william-kerr** [comment]
In the Dockerfile, I had installed that stable version just to get dependencies installed, so I could use the other version of Chrome that came with Puppeteer.  I just changed the Dockerfile to use a better method of installing dependencies, but it still works out that 2 Chrome browsers are installed (one to get dependencies installed, and the other to actually use).  I wouldn't recommend modifying the code to try to use the other Chrome browser that I install just to get dependencies; instead, just use the one that comes with Puppeteer.
